stages:
  - test

run-tests:
  stage: test
  image: python:3.7
  before_script:
    - pip install numpy
    - pip install six
    - pip install -r requirements.txt
    - pip install -r requirements_dev.txt
    - git submodule update --init --recursive --remote --merge
    - chmod +wrx $CI_PROJECT_DIR/outputs
  script:
    - python -m pytest tests
  only:
    - pushes