
language: python
stages:
  - test

jobs:
  include:
    - stage: test
      before_script:
        - mkdir -p /badc/
        - mv mini-esgf-data/test_data/badc/cmip5/ /badc/
      script: python -m pytest test