
language: python
stages:
  - test

jobs:
  include:
    - stage: test
      before_script:
        - pip install -r requirements_dev.txt
        - git submodule update --init --recursive
        - chmod +wrx outputs
      script: python -m pytest tests